---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ryanwong5/public_html/
    - /bin/cp -R _data $DEPLOYPATH
    - /bin/cp -R _drafts $DEPLOYPATH
    - /bin/cp -R _includes $DEPLOYPATH
    - /bin/cp -R _layouts $DEPLOYPATH
    - /bin/cp -R _pages $DEPLOYPATH
    - /bin/cp -R _portfolio $DEPLOYPATH
    - /bin/cp -R _publications $DEPLOYPATH
    - /bin/cp -R _sass $DEPLOYPATH
    - /bin/cp -R _talks $DEPLOYPATH
